OrangeDrangon/android-messages-desktop

src/background.ts
src/helpers/trayManager.ts

Windows 10 lauch error

---

src/background.ts

Use flashFrame() to set urgency hint on Linux systems

Set urgency hint on window when new messages are received

---

src/background.ts
src/bridge.ts
src/helpers/constants.ts

40 bugfix notification duplication

---

electron-builder.js

Set StartupWMClass in desktop file for linux builds

---

src/background.ts

A lot of experimentation will be needed here. I hope we can get this working.
Closes #157

Set user agent of the webcontents before loading the html

---

src/bridge.ts

Unread message observer stops firing

---

src/background.ts

Fix: notification not firing

---

src/menu/contextMenu.ts

use date as filename for downloaded images (issue #218)

date in filename

---

src/background.ts
src/helpers/settings.ts

Window size position

---

src/background.ts
src/helpers/autoUpdate.ts
src/helpers/settings.ts
src/menu/appMenu.ts
src/menu/contextMenu.ts
src/menu/fileMenu.ts
src/menu/helpMenu.ts
src/menu/items/checkForUpdates.ts
src/menu/items/updates.ts
src/menu/settingsMenu.ts
src/menu/trayMenu.ts

currently no button to install update

Manual Update Interaction

---

package.json
src/helpers/constants.ts
src/helpers/trayManager.ts
yarn.lock

Conditionaly generate the guid if the os is windows

---

src/bridge.ts
src/helpers/settings.ts
src/menu/settingsMenu.ts

remove the sound setting in favor of the three dot menu

---

src/background.ts

Block Google from collecting javascript errors and other data
Might need more tests. So far I see no issues.

Block Google from collecting data

---

src/background.ts
src/bridge.ts
src/menu/contextMenu.ts

The issue only appears in production builds. Development builds seem to work fine.
Resolves #342

Spellcheck Issues

---

electron-builder.js
src/background.ts

Fix windows notification center

---

src/background.ts
src/helpers/settings.ts
src/helpers/trayManager.ts
src/menu/settingsMenu.ts

Flash and dot settings

---

README.md

Per https://github.com/ScoopInstaller/Extras/pull/9028

docs: Add scoop install instructions

---

src/background.ts

Bumped User Agent String to Firefox 108 to fix Google Fi functionality

Bump User Agent String to Firefox 108

---

src/background.ts

Hide app from Dock while allowing the app to receive messages in background

Resolves #423

---

electron-builder.js

add wayland arguments

---

src/helpers/autoUpdate.ts

No update found feedback
